IOSIG_CFLAGS   = -finstrument-functions 
IOSIG_LDFLAGS  = -Wl,-wrap,fopen,-wrap,fopen64,-wrap,fclose,-wrap,fread,-wrap,fwrite,-wrap,fseek,-wrap,open,-wrap,close,-wrap,read,-wrap,write,-wrap,lseek,-wrap,lseek64,-wrap,open64 -L${IOSIG_HOME}/src/collect -liosig

CC=mpicc
CFLAGS=-Wall -g $(IOSIG_CFLAGS)
LDFLAGS=$(IOSIG_LDFLAGS)


noncontig: noncontig.o parse_cmdline.o
	$(CC) -o $@ $^ $(LDFLAGS)

clean:
	rm -f *.o

.c.o:
	$(CC) $(CFLAGS) -c $<
